site_name: chromatic_fitting
nav:
    - Home: index.md
    - API: api.md
    - Testing: test_doc.ipynb
    - Tutorials:
        - Transit Fitting: tutorial_for_transit_fitting.ipynb
        - Polynomial Fitting: tutorial_for_polynomial_fitting.ipynb

theme:
  name: "material"
repo_url: https://github.com/catrionamurray/chromatic_fitting
plugins:
  - search
  - mkdocs-jupyter
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: "numpy"
          rendering:
            show_source: false
      custom_templates: templates
      watch:
        - chromatic_fitting
